development:
  client_id: <%= ENV["GH_CLIENT_ID"] %>
  client_secret: <%= ENV["GH_CLIENT_SECRET"] %>
  access_token_url: "https://github.com/login/oauth/access_token"

test:
  client_id: <%= ENV["GH_CLIENT_ID"] %>
  client_secret: <%= ENV["GH_CLIENT_SECRET"] %>
  access_token_url: "https://github.com/login/oauth/access_token"

production:
  client_id: <%= ENV["GH_CLIENT_ID"] %>
  client_secret: <%= ENV["GH_CLIENT_SECRET"] %>
  access_token_url: "https://github.com/login/oauth/access_token"
